# makefile for project liblsm
# Created by Robert R. Snapp
# Copyright (c) 2008

HEADERS = project.h
SOURCE = cmdline.cc components.cc graphicalInterface.cc main.cc morphology.cc
OBJECTS = cmdline.o components.o graphicalInterface.o main.o morphology.o

INCLUDES = -I ../include  -I ../liblsm -I ~/include
CFLAGS =  -c $(INCLUDES) -I/usr/local/include -g -Dmac_osx

GFXLIB =  -framework GLUT -framework OpenGL \
          -framework Foundation  -framework vecLib 


#GFXLIB = -L$(GLUI)/lib -lglui -framework GLUT -framework OpenGL \
#         -framework vecLib -framework Foundation
#LIBPATH = -L/sw/lib -L/usr/local/lib -L/usr/X11R6/lib
#LIBS = -lglut -lGLU -lGL -lXmu -lXext -lX11 -lm

LIBS = ~/lib/liblsm.dylib $(GFXLIB) -lm 
LIBPATH = -L ../liblsm -L ~/lib -rpath ~/lib

CPP = g++

.cc.o:
	${CPP} ${CFLAGS} $<

nuclearSlice: ${OBJECTS}
	${CPP} -M -t -o $@ ${OBJECTS} ${LIBPATH} ${LIBS}

clean:
	rm $(OBJECTS) nuclearSlice

all: nuclearSlice
