# makefile for project liblsm
# Created by Robert R. Snapp
# Copyright (c) 2008

HEADERS = project.h
SOURCE = cmdline.cc components.cc graphicalInterface.cc main.cc morphology.cc
OBJECTS = cmdline.o components.o graphicalInterface.o main.o morphology.o

INCLUDES = -I/usr/X11R6/include -I/usr/include -I../include  -I ~/include
CFLAGS =  -c $(INCLUDES) -I/usr/local/include -g -Wabi -Weffc++ -Wreorder -pedantic -Wall

#GL_LIBS = -L /usr/X11R6/lib  -L/usr/lib/w32api -L/usr/lib -lglut -lGLU -lGL
GL_LIBS = -L /usr/X11R6/lib   -L/usr/lib -lglut -lGLU -lGL -lXmu -lXext -lX11 -lm
LSM_LIB = -L ~/lib -llsm
LIBS = $(LSM_LIB) $(GL_LIBS)

#GFXLIB = -L$(GLUI)/lib -lglui -framework GLUT -framework OpenGL \
#         -framework vecLib -framework Foundation
#LIBPATH = -L/sw/lib -L/usr/local/lib -L/usr/X11R6/lib
#LIBS = -lglut -lGLU -lGL -lXmu -lXext -lX11 -lm

#LIBS = ~/lib/liblsm.dylib $(GFXLIB) -lm 
#LIBPATH = -L ../liblsm -L ~/lib -rpath ~/lib

CPP = g++

.cc.o:
	${CPP} ${CFLAGS} $<

nuclearSlice: ${OBJECTS}
	${CPP}  -o $@ -Xlinker --enable-auto-import ${OBJECTS} ${LIBS}

clean:
	rm $(OBJECTS) nuclearSlice.exe

all: nuclearSlice
